name: README Repos List
on: ["push", "pull_request"]
  #  schedule:
  #    - cron: "0 0 * * 1"

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Run readme-repos-list
        uses: koj-co/readme-repos-list@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: "Octocat in:readme user:savvagen"
          max: 10